version: '3'

services:
  app:
    build: .
    ports:
      - '8080:8080'
    container_name: 'credijusto'
    environment:
      - NODE_ENV=production
      - PORT=8080
      - MONGODB_URL=mongodb://mongo:27017/credijusto
    volumes:
      - './src:/usr/src/app/src'
      - './router:/usr/src/app/router'
      - './server.js:/usr/src/app/server.js'
    links:
      - mongo
      - redis
    depends_on:
      - mongo
      - redis
  mongo:
    image: mongo:3.4
    volumes:
      - mongodb:/data/db
      - mongodb_config:/data/configdb
    ports:
      - '27017:27017'
  redis:
    image: redis
    volumes:
      - /data/db/redis
    ports:
      - "6379:6379"
volumes:
  mongodb:
  mongodb_config:
